# Generated by Django 5.0.6 on 2026-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='NOT-PROVIDED', max_length=20),
        ),
    ]
